### ISSUE TITLE
Generated captions from models

### ISSUE THREAD

**Issue by EileenWang1996** [zjr2000/GVL#1]
Hello, thank you for sharing the code! Would you also be able to provide the predicted captions from your model? I'm interested in the dense and paragraph captioning predictions for the ActivityNet dataset as I want to use it for my own evaluation.

**Comment by ttengwang** [comment]
@EileenWang1996 Thanks for your interest in our work. I have uploaded them to https://drive.google.com/drive/folders/1EZuwAgiRKu8TW-_p9l9kMzAzEAEwSfee?usp=sharing

**Comment by EileenWang1996** [comment]
Thank you for your reply :) 
I noticed that you are also the author for PDVC: https://arxiv.org/pdf/2108.07781.pdf
Do you happen to have the predicted captions for this as well? I'm interested in the ones that reproduce the results from Table 3 and 4 for both ground-truth and predicted proposals.

**Comment by ttengwang** [comment]
The original files are lost. But I believe it is easy to reproduce all results using the pretrained checkpoints at https://github.com/ttengwang/PDVC#performance

**Comment by EileenWang1996** [comment]
Okay, thank you so much!

**Comment by EileenWang1996** [comment]
Okay thank you so much
