### ISSUE TITLE
opt.use_cider_rouge_as_current_dvc_score参数缺失

### ISSUE THREAD

**Issue by llljjj88** [zjr2000/GVL#2]
感谢你的分享，在复现这篇论文的时候训练时候出现opt.use_cider_rouge_as_current_dvc_score参数缺失，请问这个应该是什么呢

**Comment by zjr2000** [comment]
感谢您的关注，这个参数可以删去或直接设为False。之前清洗代码时遗漏了这里，我们会尽快更新。

**Comment by zjr2000** [comment]
c464e2e

**Comment by llljjj88** [comment]
感谢您的回复，很好的解决我的疑惑

**Comment by llljjj88** [comment]
您好，在使用anet_c3d_dvc_rl.yml中pretrain_path:PRETRAINED_CHECKPOINT应该是什么呢？

**Comment by zjr2000** [comment]
> 您好，在使用anet_c3d_dvc_rl.yml中pretrain_path:PRETRAINED_CHECKPOINT应该是什么呢？

训强化学习前需要加载预训练的权重，pretrain_path是到权重文件的路径，需要自己设置

**Comment by llljjj88** [comment]
预训练的权重文件去哪里下载

**Comment by zjr2000** [comment]
你可以使用另一个[cfg](https://github.com/zjr2000/GVL/blob/master/cfgs/anet_tsp_msvg_dvc_pc.yml )文件训练一个模型。或者去README里给出的[google drive](https://drive.google.com/drive/folders/1vvr4kYI7xGklOdgyQU5L34W2ZxRQzspK)下载

**Comment by llljjj88** [comment]
感谢您的分享
